### ISSUE TITLE
Praise for the great work

### ISSUE THREAD

**Issue by SlootSantos** [chainifynet/aws-encryption-sdk-go#171]
Hey Andrew,

I just want to praise your efforts to support the AWS encryption SDK for Go! Thank you very much for getting the Go communicate kick-started like that. Encryption is a very very very important issue. Unfortunately, we see too many teams/companies not applying the appropriate amount of paranoia when it comes to handling data. Loosing data is always bad.. loosing unencrypted data is a whole lot worse. 
This package you’re building is making it a lot easier to adopt client side encryption in a Go+AWS context!

Again, thank you very much.
Have a merry Christmas!

**Comment by wobondar** [comment]
Hey @SlootSantos,

Thank you so much for your kind words and for recognising the importance of the AWS Encryption SDK for Go. I completely agree that encryption is a critical aspect of data security, and it's heartening to see the community's awareness and commitment to this.

This SDK aims to fill the gap of the absence of a Go implementation to make client-side encryption more accessible and straightforward for developers working in a Go+AWS environment. I'm incredibly pleased to hear that this goal is being achieved.

Your comment about the often-underestimated need for data protection resonates deeply with me. It's crucial for teams and companies to adopt a proactive approach to data security, especially in today's digital landscape, where data breaches can have significant consequences.

I'm glad to contribute to the project that helps safeguard data and advance the Go community. Your support and feedback are invaluable in improving and evolving SDK.

I also, with a delay, wish you a Merry Christmas and Happy New Year, and I look forward to more interactions and collaborations in the future!

Best regards,
Andrew
